#!/bin/bash

verbose_echo() {
    if [ ! -z $CLINK_VERBOSITY ]; then
        fd="--stderr"
    fi
    logger --id $fd --tag "clink" -- "$@"
}

need_item() {
    if [ -z $1 ]; then
        echo "Not enough input"
        exit 1
    fi
}

display_usage() {
    echo "usage: $(basename $0) [--install-shell-func] | [--get IMAGE] | [--help]"
    echo
    echo "Flags:"
    echo "  --install-shell-func IMAGE"
    echo "  --get IMAGE"
    echo
    echo "Environment variables:"
    echo "  CLINK_VERBOSITY: When set, clink will echo extra information."
    echo "  DOCKER_HUB_USER: Set this to the name of a Docker hub user or private registry namespace."
    echo " CLINK_REGISTRIES: Semicolon-separated list of private registry namespaces."
    echo "  CLINK_RUN_FLAGS: Extra flags to pass to docker run."
    echo
    echo "Help:"
    echo "  -h, --help"
    echo
    echo "This program should not be executed directly in most cases. Instead, "
    echo "you should source it by adding the following line to your profile:"
    echo
    echo "source $(readlink -f $0)"
}

run_cli() {
    case "$1" in
    --install-shell-func)
        # fixme: not sure what this should actually do
        :
        ;;
    --ls|--list)
        images=$(docker images | grep -v ^REPOSITORY | cut -d" " -f1 | sort | uniq)
        echo "$images"
        ;;
    --link)
        shift
        run_source
        echo "  Make sure your image is tagged $1:"
        echo "docker tag IMAGE $1"
        echo "  Then create a symlink in your path to clink:"
        echo "ln -s $SCRIPT_DIR/clink $HOME/bin/$1"
        ;;
    --get)
        shift
        need_item $1
        image=$1
        docker pull $image
        ;;
    -h|--help)
        display_usage
        exit 1
        ;;
    *)
        need_item $0
        image=$(basename $0)
        if [ $image = "clink" ]; then
            display_usage && return
        fi
        echo "Running: $image $@"
        run_source
        command_not_found "$image" "$@"
    esac
}

run_source() {
    # Bail if we are already in a container
    [ -e /.dockerenv ] && echo "already in a container!" && return

    # If we are symlink, find out our true path.
    # (Note: we only dereference one level.)
    if [[ -L "$SCRIPT_FILE" ]]; then
        SCRIPT_FILE="$(readlink "$SCRIPT_FILE")"
    fi

    SCRIPT_DIR="$(dirname "$SCRIPT_FILE")"
    source "$SCRIPT_DIR/source_commands"
}

# We need to find out:
# - where we are installed,
# - if we are executed or sourced.
# Detection mechanisms will depend on the shell used.

if [[ -n "${BASH_SOURCE[0]}" ]]; then
    # This special variable is set only in bash.
    # It is *always* the name of the file.
    SCRIPT_FILE="${BASH_SOURCE[0]}"
    # If we are executed, $0 is the name of the file.
    if [[ "$SCRIPT_FILE" = "$0" ]]; then
        SCRIPT_MODE=exec
    else
        SCRIPT_MODE=source
    fi
fi

if [[ -n "$ZSH_EVAL_CONTEXT" ]]; then
    # This special variable is set only in zsh.
    SCRIPT_FILE="$0"
    # ZSH_EVAL_CONTEXT is "toplevel" when we are executed,
    # and "toplevel:file" if we are sourced.
    if [[ "$ZSH_EVAL_CONTEXT" = toplevel ]]; then
        SCRIPT_MODE=exec
    else
        SCRIPT_MODE=source
    fi
fi

case "$SCRIPT_MODE" in
    source) run_source;;
    exec) run_cli "$@";;
    *) echo "Sorry, I could not detect which shell you are using.";;
esac


